[package]
name = "shaders"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse", "display"] }
hassle-rs = "0.11"
shaderc = "0.8"